### ISSUE TITLE
O(1) solution

### ISSUE THREAD

**Issue by ankit167** [wzhishen/cracking-the-coding-interview#4]
https://github.com/wzhishen/cracking-the-coding-interview/blob/08b46140d38d4d6745c6c55a8fa2da2ad028cc35/src/chap18/Q05.java#L39

Is it possible to have to an O(1) solution to find the minimum distance between any two words, after doing the some magic in the pre-processing logic?

**Comment by wzhishen** [comment]
Potentially we could. Ie., in another preprocess step, we can run `findShortextPath2` repeatedly against any potential queries `(word1, word2)` pairs, then create a `(word1, word2)` to `minDistance` map. Then we could have O(1) access. Let's say it is called `findShortextPath3`.

However, in reality `findShortextPath3` is usually not practical, given that the text sample is usually massive with fewer duplicate words, and query word combination is indefinite. The needed space would be way higher than imagined, potentially exponential.

Note that for solution `findShortextPath2`, the worst case happens on a text file that contains highly duplicate words with queries on those words, whereas `findShortextPath3` in such cases would be a more optimal thought - just a one time effort running over duplicate words' indexes. For a more usual text file, duplicate words would happen much less frequently, `findShortextPath2` will act better.

In a real software system, a typical caching layer between application layer and backend processing layer can act as such "map". Results of hot queries are cached, so that these requests could be handled at O(1), while ensuring a reasonably manageable size of cache space, when cold ones are permitted to process at a longer time.

These are all good points to discuss with your interviewer. Because a good interview process is to let  interviewer know what you can think about given a fixed topic, apart from your code presented. Good luck!
